const MIN_SIZE = 400;
let enabled = true, srcLang = "ja", dstLang = "vi", pruneFrame = 0, currentRequestId = null, port = null;
const overlays = new Map(), imageRequests = new WeakMap(), jobBindings = new Map(), pendingScopes = new Map(), activeScopeMessages = new Map();

chrome.storage.local.get(["enabled", "srcLang", "dstLang"]).then((v) => { enabled = v.enabled !== false; srcLang = v.srcLang || "ja"; dstLang = v.dstLang || "vi"; });
chrome.storage.onChanged.addListener((ch) => { if (ch.srcLang) srcLang = ch.srcLang.newValue; if (ch.dstLang) dstLang = ch.dstLang.newValue; if (ch.enabled) { enabled = ch.enabled.newValue; for (const { container } of overlays.values()) container.style.display = enabled ? "" : "none"; } });
chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => { if (msg.type === "translatePage") { translatePage(msg.scope, msg.srcLang, msg.dstLang).then(sendResponse); return true; } if (msg.type === "prewarmPage") { prewarmPage(msg.srcLang); sendResponse({ ok: true }); } });

function translationPort() { if (port) return port; port = chrome.runtime.connect({ name: "translation" }); port.onMessage.addListener(handleEvent); port.onDisconnect.addListener(() => { port = null; const message = activeScopeMessages.get(currentRequestId); if (message && pendingScopes.has(currentRequestId)) queueMicrotask(() => translationPort().postMessage({ ...message, replaces_request_id: null })); }); return port; }
function snapshotJobs(scope, requestId, requestSrcLang, requestDstLang) { const images = [...document.querySelectorAll("img")], candidates = selectCandidates(images, scope, innerWidth, innerHeight, MIN_SIZE); for (const img of images) if (scope === "loaded" || isViewportVisible(img, innerWidth, innerHeight)) { imageRequests.set(img, requestId); const o = overlays.get(img); if (o && (o.srcLang !== requestSrcLang || o.dstLang !== requestDstLang || sourceSignature(img) !== o.sourceSignature)) removeOverlay(img); } return candidates.map((c) => { const jobId = crypto.randomUUID(), cropSignature = JSON.stringify(c.crop || "full"), o = overlays.get(c.img); if (o && o.cropSignature !== cropSignature) removeOverlay(c.img); jobBindings.set(jobId, { img: c.img, requestId, source: c.source, sourceSignature: c.source_signature, cropSignature, scope, srcLang: requestSrcLang, dstLang: requestDstLang }); return { job_id: jobId, source_url: c.source, crop: c.crop, natural_width: c.natural_width, natural_height: c.natural_height, distance: c.distance, priority: isViewportVisible(c.img, innerWidth, innerHeight) ? 0 : 1 }; }); }
function translatePage(scope, requestSrcLang = srcLang, requestDstLang = dstLang) { const requestId = crypto.randomUUID(), replacesRequestId = currentRequestId; currentRequestId = requestId; srcLang = requestSrcLang; dstLang = requestDstLang; let jobs; try { jobs = snapshotJobs(scope, requestId, srcLang, dstLang); } catch (error) { return Promise.resolve({ ok: false, error: error.message }); } const done = new Promise((resolve) => pendingScopes.set(requestId, { resolve, startedAt: performance.now(), firstOverlayMs: null })); const message = { type: "start_scope", request_id: requestId, replaces_request_id: replacesRequestId, scope, src_lang: srcLang, dst_lang: dstLang, jobs }; activeScopeMessages.set(requestId, message); translationPort().postMessage(message); return done; }
function validBinding(event) { const b = jobBindings.get(event.job_id); return b && b.requestId === event.request_id && imageRequests.get(b.img) === event.request_id && b.img.isConnected && isCurrentSource(b.img, b.source, b.scope) && sourceSignature(b.img) === b.sourceSignature && b.srcLang === srcLang && b.dstLang === dstLang ? b : null; }
function handleEvent(event) { if (event.type === "translation") { const b = validBinding(event); if (b) upsertOverlayBlock(b.img, b, event); return; } if (event.type === "image_done") { const b = validBinding(event); if (b && event.translated === 0) removeOverlay(b.img); return; } const pending = pendingScopes.get(event.request_id); if (!pending) return; if (event.type === "scope_error") { pendingScopes.delete(event.request_id); activeScopeMessages.delete(event.request_id); pending.resolve({ ok: false, error: event.code || event.error }); return; } if (event.type === "scope_done") { pendingScopes.delete(event.request_id); activeScopeMessages.delete(event.request_id); for (const [id, b] of jobBindings) if (b.requestId === event.request_id) jobBindings.delete(id); pending.resolve({ ok: true, images: event.images, blocks: event.translated, failed: event.failed, cacheHit: event.cache_hit === true, firstOverlayMs: pending.firstOverlayMs }); } }
function ensureOverlay(img, binding, event) { let o = overlays.get(img); if (o && o.requestId !== binding.requestId) { if (o.source === binding.source && o.sourceSignature === binding.sourceSignature && o.cropSignature === binding.cropSignature && o.srcLang === binding.srcLang && o.dstLang === binding.dstLang) o.requestId = binding.requestId; else { removeOverlay(img); o = null; } } if (o) return o; const container = document.createElement("div"); container.className = "mt-overlay"; if (!enabled) container.style.display = "none"; document.body.appendChild(container); o = { container, source: binding.source, sourceSignature: binding.sourceSignature, cropSignature: binding.cropSignature, scope: binding.scope, requestId: binding.requestId, srcLang: binding.srcLang, dstLang: binding.dstLang, imageW: event.image_w, imageH: event.image_h, blocks: new Map(), resizeObserver: new ResizeObserver(() => position(img)) }; overlays.set(img, o); o.resizeObserver.observe(img); return o; }
function upsertOverlayBlock(img, binding, event) { const o = ensureOverlay(img, binding, event); let b = o.blocks.get(event.block_id); if (!b) { const element = document.createElement("div"); element.className = "mt-bubble"; o.container.appendChild(element); b = { element, bbox: event.bbox }; o.blocks.set(event.block_id, b); } b.bbox = event.bbox; b.element.textContent = event.trans_text; position(img); const pending = pendingScopes.get(binding.requestId); if (pending && pending.firstOverlayMs == null) { pending.firstOverlayMs = Math.round(performance.now() - pending.startedAt); translationPort().postMessage({ type: "render_metric", request_id: binding.requestId, first_overlay_ms: pending.firstOverlayMs }); } }
function removeOverlay(img) { const o = overlays.get(img); if (!o) return; o.resizeObserver.disconnect(); o.container.remove(); overlays.delete(img); }
function pruneOverlays() { for (const [img, o] of overlays) if (!img.isConnected || sourceSignature(img) !== o.sourceSignature || !isCurrentSource(img, o.source, o.scope)) removeOverlay(img); }
function schedulePrune() { if (!pruneFrame) pruneFrame = requestAnimationFrame(() => { pruneFrame = 0; pruneOverlays(); }); }
function position(img) { const o = overlays.get(img); if (!o) return; const r = img.getBoundingClientRect(); Object.assign(o.container.style, { left: r.left + scrollX + "px", top: r.top + scrollY + "px", width: r.width + "px", height: r.height + "px" }); for (const block of o.blocks.values()) { const [x, y, w, h] = block.bbox, el = block.element; Object.assign(el.style, { left: x * r.width / o.imageW + "px", top: y * r.height / o.imageH + "px", width: w * r.width / o.imageW + "px", height: h * r.height / o.imageH + "px" }); fitText(el); } }
function fitText(el) { let size = 18; el.style.fontSize = size + "px"; while (size > 10 && (el.scrollHeight > el.clientHeight || el.scrollWidth > el.clientWidth)) el.style.fontSize = --size + "px"; }
function repositionOverlays() { schedulePrune(); for (const img of overlays.keys()) position(img); }
async function prewarmPage(requestSrcLang) { try { const jobs = selectCandidates(document.querySelectorAll("img"), "visible", innerWidth, innerHeight, MIN_SIZE); const selected = jobs.sort((a, b) => visibleArea(b.img, innerWidth, innerHeight) - visibleArea(a.img, innerWidth, innerHeight))[0]; if (selected) await chrome.runtime.sendMessage({ type: "prewarmJob", source_url: selected.source, crop: selected.crop, natural_width: selected.natural_width, natural_height: selected.natural_height, src_lang: requestSrcLang }); } catch (error) { console.warn("[MangaTranslator] prewarm:", error); } }
new MutationObserver(schedulePrune).observe(document.body, { subtree: true, childList: true, attributes: true, attributeFilter: ["src", "srcset", "sizes", "media", "type"] }); new ResizeObserver(repositionOverlays).observe(document.documentElement); window.addEventListener("resize", repositionOverlays);
